name: VHDL Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install NVC
        uses: nickg/setup-nvc@v1
        with:
          version: '1.20.1'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run float_add tests
        working-directory: tb/float_add_tb
        run: make

      - name: Run float_mult tests
        working-directory: tb/float_mult_tb
        run: make

      - name: Run Raw Decimator tests
        working-directory: tb/raw_decimator_tb
        run: make

      - name: Run Decimator Comb tests
        working-directory: tb/dec_cic_filter_tb
        run: make

      - name: Run Complex Mult tests
        working-directory: tb/complex_mult_tb
        run: make

      - name: Run Atan2 Cordic tests
        working-directory: tb/atan2_cordic_tb
        run: make